### ISSUE TITLE
Distraction free mode

### ISSUE THREAD

**Issue by royanger** [Melkeydev/astrostation#237]
As we flesh out Astrostation and add more features, a distraction free mode would be super useful. 

Acceptance criteria:

- added an interface and store to handle whether the mode is on or off
- mode should either heavily dim or hide everything but the clock

Consideration:

- should this be a widget, with a toggle to show or hide it? I think this is better suited as a button in the top right. Thoughts @Melkeydev

**Comment by hhthacker** [comment]
🤗

**Comment by Melkeydev** [comment]
@hhthacker Do you want this one

**Comment by lak7** [comment]
I noticed that there hasn't been any progress made on this issue for the past three weeks, and I'm wondering if there are any obstacles preventing you from working on it.
I would like to propose taking over this task if it's possible. Else I would be happy to assist you in any way possible.

**Comment by royanger** [comment]
@hhthacker How goes progress with this Issue? Please let us know how long you need to complete. @lak7, let's give Heather a few days to respond. If she can't handle it or we don't hear from about it within a week you can take over.

**Comment by Melkeydev** [comment]
@lak7 Are you still interested in handling this issue?
