### ISSUE TITLE
Deleting a Task does not allow you to cancel

### ISSUE THREAD

**Issue by justnat3** [Melkeydev/astrostation#246]
![image](https://user-images.githubusercontent.com/58314490/227785575-c425335c-145e-4d9c-b835-2d3cd9acbd54.png)

Even when you click outside or escape the alert box, it still deletes the task. 

Cheers, -Nate

**Comment by justnat3** [comment]
Ideally this is a modal or an alert that is cancel-able :)

**Comment by herropaul** [comment]
Ello good sir, I'd like to take this 😎

**Comment by justnat3** [comment]
> Ello good sir, I'd like to take this 😎 

For sure! There's individual modals in the project already. For example, components/TaskTracker/InfoModal you can take inspiration from.

I cant mark you as a contributor for this issue, but I have done a lot to task-tracker consider It yours

**Comment by herropaul** [comment]
Awesome, im def gonna checkout the infomodal then 👍 .  I'll let you know if i have any questions along the way as well

**Comment by herropaul** [comment]
<img width="382" alt="Screen Shot 2023-03-30 at 6 00 03 PM" src="https://user-images.githubusercontent.com/35973829/228996619-1a030d74-5bdb-4f8b-9ee0-dd08289319be.png">
I ended up using ur InfoModal as reference @justnat3 haha. Thoughts on the delete modal? Any touch ups or changes you think?

**Comment by justnat3** [comment]
> I ended up using ur InfoModal as reference @justnat3 haha. Thoughts on the delete modal? Any touch ups or changes you think?

From just looking at it, I personally like the it the overall idea. Good job! 

I would love to be able to look at it from a browser(vercel preview) if you want to link this issue to a PR. If you don't feel its quite ready feel free to set the PR as a **WIP**

**Comment by herropaul** [comment]
> > I ended up using ur InfoModal as reference @justnat3 haha. Thoughts on the delete modal? Any touch ups or changes you think?
> 
> From just looking at it, I personally like the it the overall idea. Good job!
> 
> I would love to be able to look at it from a browser(vercel preview) if you want to link this issue to a PR. If you don't feel its quite ready feel free to set the PR as a **WIP**

Appreciate it man! 

I'll be working on this today, so I don't mind setting up a PR to preview it. I'll make sure its **WIP** as well

**Comment by Melkeydev** [comment]
@herropaul Do you have any branches on this? Wondering If i should close this issue due to inactivity

**Comment by herropaul** [comment]
@Melkeydev I do have a branch on this, how should we got about it? It's still old too so idk if much changed since
