### ISSUE TITLE
Invalid Spotify url

### ISSUE THREAD

**Issue by rayenCtrl** [Melkeydev/astrostation#305]
Hi Melkey, I noticed that there's an issue with Astronation when pasting Spotify song URLs. Could you please look into this and assist in resolving the problem? Thank you!

![image_2023-11-02_204815045](https://github.com/MelkeyOSS/astrostation/assets/69252534/a1b0f01d-5802-4e15-a96e-d39e4c5d1793)

**Comment by Melkeydev** [comment]
Ah I see the issue.
This is because it is a singular track you are trying to paste.
The Spotify SDK only accepts playlists right now!
