### ISSUE TITLE
Add a developer news feed

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/astrostation#78]
Twitch Suggestion by whatizit:
Add a developer news feed to the application

**Comment by herropaul** [comment]
Ohh I like this feature. Is this gonna be like web scraping from hackernews and putting it into a news feed widget?

**Comment by Melkeydev** [comment]
Yeah! Exactly

**Comment by probablyArth** [comment]
I can work on this👌

**Comment by probablyArth** [comment]
This API looks usable https://github.com/HackerNews/API#new-top-and-best-stories

**Comment by royanger** [comment]
WIP PR for this. https://github.com/MelkeyOSS/astrostation/pull/227
